#!/bin/sh
#
if [ $# -le 3 ] ; then
   echo "usage: $0 output dhr list_of_grib_Files"
   echo " input grib files must by synoptic files and in cronological order"
   echo " input grib files must have an identical record order"
   exit 8
fi

tmp1=/tmp/mk_ave.tmp.$$
CODE=/home/ebis/gribw/rr

output=$1
dhr=$2
shift 2

$CODE/grib_merge $tmp1 $*

$CODE/mk_ave_eta_fast.x $tmp1 $output $dhr

rm $tmp1

exit
